#!/bin/sh

modprobe i2c-algo-bit

insmod adv717x.o
# pixelport_16bit=1 pixelport_other_pal=0 swap_redblue_pal=0 color_bars=1
insmod bt865.o
# color_bars=1
insmod em8300.o
# use_bt865=0 bt865_ucode_timeout=1 dicom_fix=0 dicom_control=0 dicom_other_pal=0
