#!/bin/sh -e

# movedoc - function to make the transition /usr/doc -> /usr/share/doc
movedoc()
{
   PKG=em8300
   OLD=/usr/doc/$PKG
   if test -h $OLD; then
     rm -f $OLD
   fi
}


case "$1" in
remove|deconfigure)
    movedoc
    rm -f /etc/dxr3.ux
    ;;
esac
